name: manage-azure-policy-ed56efee
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Append_Cost_Center_Tag_240674_e15870cf-054c-4e4e-a2a1-5be333795633/**'
#      - .github/workflows/manage-azure-policy-ed56efee.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ed56efee}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Append_Cost_Center_Tag_240674_e15870cf-054c-4e4e-a2a1-5be333795633/**
